@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_TOP_DOWN()
title Publish and consume messages

Boundary(app, "Your application"){
    Boundary(appProducer, "Some service with publisher"){
        System_Ext(publisher, "Producer", "Produce message")
    }
    Boundary(appConsumer1, "Some service with consumer N"){
        System_Ext(consumer11, "Consumer N.1", "Consume and process message")
        System_Ext(consumer12, "Consumer N.M", "Consume and process message")
    }
}
Boundary(redbus, "RED Bus"){
    Person(human, "Administrator")
    System(databus, "DataBus", "Send message to MQ. Store MQ consumers, send message to consumers, and receive processing results.", "Go")
    System(repeater, "Repeater", "Reprocesses failed messages by consumers according to the retry strategy.", "Go")
    System(admin, "Admin panel", "Viewing the actual status and managing the retry system.", "Vue")
}

BiRel_L(databus, repeater, "Save failed message and process them")
BiRel_D(repeater, consumer11, "Process message", "GRPC")
BiRel_D(repeater, consumer12, "Process message", "GRPC")
Rel_R(human, admin, "View and manage")
Rel_Down(admin, databus, "Get data")

Rel(publisher, databus, "Publish message", "GRPC")
BiRel_D(databus, consumer11, "Consume message", "GRPC")
BiRel_D(databus, consumer12, "Consume message", "GRPC")

@enduml