// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.36.0
// source: internal/api/admincontrol/admincontrol.proto

package admincontrol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_api_admincontrol_admincontrol_proto_rawDescGZIP(), []int{0}
}

type StateSnapshot struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConsumeTopicCount int32                  `protobuf:"varint,1,opt,name=consume_topic_count,json=consumeTopicCount,proto3" json:"consume_topic_count,omitempty"`
	ConsumerCount     int32                  `protobuf:"varint,2,opt,name=consumer_count,json=consumerCount,proto3" json:"consumer_count,omitempty"`
	RepeatAllCount    int32                  `protobuf:"varint,3,opt,name=repeat_all_count,json=repeatAllCount,proto3" json:"repeat_all_count,omitempty"`
	RepeatFailedCount int32                  `protobuf:"varint,4,opt,name=repeat_failed_count,json=repeatFailedCount,proto3" json:"repeat_failed_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StateSnapshot) Reset() {
	*x = StateSnapshot{}
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateSnapshot) ProtoMessage() {}

func (x *StateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateSnapshot.ProtoReflect.Descriptor instead.
func (*StateSnapshot) Descriptor() ([]byte, []int) {
	return file_internal_api_admincontrol_admincontrol_proto_rawDescGZIP(), []int{1}
}

func (x *StateSnapshot) GetConsumeTopicCount() int32 {
	if x != nil {
		return x.ConsumeTopicCount
	}
	return 0
}

func (x *StateSnapshot) GetConsumerCount() int32 {
	if x != nil {
		return x.ConsumerCount
	}
	return 0
}

func (x *StateSnapshot) GetRepeatAllCount() int32 {
	if x != nil {
		return x.RepeatAllCount
	}
	return 0
}

func (x *StateSnapshot) GetRepeatFailedCount() int32 {
	if x != nil {
		return x.RepeatFailedCount
	}
	return 0
}

type TopicStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Topic               `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicStats) Reset() {
	*x = TopicStats{}
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicStats) ProtoMessage() {}

func (x *TopicStats) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicStats.ProtoReflect.Descriptor instead.
func (*TopicStats) Descriptor() ([]byte, []int) {
	return file_internal_api_admincontrol_admincontrol_proto_rawDescGZIP(), []int{2}
}

func (x *TopicStats) GetList() []*Topic {
	if x != nil {
		return x.List
	}
	return nil
}

type Topic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Partitions    []*Partition           `protobuf:"bytes,2,rep,name=partitions,proto3" json:"partitions,omitempty"`
	Groups        []*Group               `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topic) Reset() {
	*x = Topic{}
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_internal_api_admincontrol_admincontrol_proto_rawDescGZIP(), []int{3}
}

func (x *Topic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Topic) GetPartitions() []*Partition {
	if x != nil {
		return x.Partitions
	}
	return nil
}

func (x *Topic) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type Partition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	FirstOffset   int64                  `protobuf:"varint,2,opt,name=first_offset,json=firstOffset,proto3" json:"first_offset,omitempty"`
	LastOffset    int64                  `protobuf:"varint,3,opt,name=last_offset,json=lastOffset,proto3" json:"last_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Partition) Reset() {
	*x = Partition{}
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Partition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Partition) ProtoMessage() {}

func (x *Partition) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Partition.ProtoReflect.Descriptor instead.
func (*Partition) Descriptor() ([]byte, []int) {
	return file_internal_api_admincontrol_admincontrol_proto_rawDescGZIP(), []int{4}
}

func (x *Partition) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Partition) GetFirstOffset() int64 {
	if x != nil {
		return x.FirstOffset
	}
	return 0
}

func (x *Partition) GetLastOffset() int64 {
	if x != nil {
		return x.LastOffset
	}
	return 0
}

type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Partitions    []*GroupPartition      `protobuf:"bytes,2,rep,name=partitions,proto3" json:"partitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_internal_api_admincontrol_admincontrol_proto_rawDescGZIP(), []int{5}
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetPartitions() []*GroupPartition {
	if x != nil {
		return x.Partitions
	}
	return nil
}

type GroupPartition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	ConsumerId    string                 `protobuf:"bytes,3,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	ConsumerState string                 `protobuf:"bytes,4,opt,name=consumer_state,json=consumerState,proto3" json:"consumer_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupPartition) Reset() {
	*x = GroupPartition{}
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupPartition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupPartition) ProtoMessage() {}

func (x *GroupPartition) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupPartition.ProtoReflect.Descriptor instead.
func (*GroupPartition) Descriptor() ([]byte, []int) {
	return file_internal_api_admincontrol_admincontrol_proto_rawDescGZIP(), []int{6}
}

func (x *GroupPartition) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *GroupPartition) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GroupPartition) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *GroupPartition) GetConsumerState() string {
	if x != nil {
		return x.ConsumerState
	}
	return ""
}

type RetryStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*RetryStat           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryStats) Reset() {
	*x = RetryStats{}
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryStats) ProtoMessage() {}

func (x *RetryStats) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryStats.ProtoReflect.Descriptor instead.
func (*RetryStats) Descriptor() ([]byte, []int) {
	return file_internal_api_admincontrol_admincontrol_proto_rawDescGZIP(), []int{7}
}

func (x *RetryStats) GetList() []*RetryStat {
	if x != nil {
		return x.List
	}
	return nil
}

type RetryStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	AllCount      int32                  `protobuf:"varint,3,opt,name=all_count,json=allCount,proto3" json:"all_count,omitempty"`
	FailedCount   int32                  `protobuf:"varint,4,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	LastError     string                 `protobuf:"bytes,5,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryStat) Reset() {
	*x = RetryStat{}
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryStat) ProtoMessage() {}

func (x *RetryStat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryStat.ProtoReflect.Descriptor instead.
func (*RetryStat) Descriptor() ([]byte, []int) {
	return file_internal_api_admincontrol_admincontrol_proto_rawDescGZIP(), []int{8}
}

func (x *RetryStat) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *RetryStat) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *RetryStat) GetAllCount() int32 {
	if x != nil {
		return x.AllCount
	}
	return 0
}

func (x *RetryStat) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *RetryStat) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type RestartFailedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartFailedRequest) Reset() {
	*x = RestartFailedRequest{}
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartFailedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartFailedRequest) ProtoMessage() {}

func (x *RestartFailedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartFailedRequest.ProtoReflect.Descriptor instead.
func (*RestartFailedRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_admincontrol_admincontrol_proto_rawDescGZIP(), []int{9}
}

func (x *RestartFailedRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *RestartFailedRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

var File_internal_api_admincontrol_admincontrol_proto protoreflect.FileDescriptor

const file_internal_api_admincontrol_admincontrol_proto_rawDesc = "" +
	"\n" +
	",internal/api/admincontrol/admincontrol.proto\x12\x16redbus.admincontrol.v1\"\a\n" +
	"\x05Empty\"\xc0\x01\n" +
	"\rStateSnapshot\x12.\n" +
	"\x13consume_topic_count\x18\x01 \x01(\x05R\x11consumeTopicCount\x12%\n" +
	"\x0econsumer_count\x18\x02 \x01(\x05R\rconsumerCount\x12(\n" +
	"\x10repeat_all_count\x18\x03 \x01(\x05R\x0erepeatAllCount\x12.\n" +
	"\x13repeat_failed_count\x18\x04 \x01(\x05R\x11repeatFailedCount\"?\n" +
	"\n" +
	"TopicStats\x121\n" +
	"\x04list\x18\x01 \x03(\v2\x1d.redbus.admincontrol.v1.TopicR\x04list\"\x95\x01\n" +
	"\x05Topic\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12A\n" +
	"\n" +
	"partitions\x18\x02 \x03(\v2!.redbus.admincontrol.v1.PartitionR\n" +
	"partitions\x125\n" +
	"\x06groups\x18\x03 \x03(\v2\x1d.redbus.admincontrol.v1.GroupR\x06groups\"g\n" +
	"\tPartition\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x12!\n" +
	"\ffirst_offset\x18\x02 \x01(\x03R\vfirstOffset\x12\x1f\n" +
	"\vlast_offset\x18\x03 \x01(\x03R\n" +
	"lastOffset\"c\n" +
	"\x05Group\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12F\n" +
	"\n" +
	"partitions\x18\x02 \x03(\v2&.redbus.admincontrol.v1.GroupPartitionR\n" +
	"partitions\"\x88\x01\n" +
	"\x0eGroupPartition\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x1f\n" +
	"\vconsumer_id\x18\x03 \x01(\tR\n" +
	"consumerId\x12%\n" +
	"\x0econsumer_state\x18\x04 \x01(\tR\rconsumerState\"C\n" +
	"\n" +
	"RetryStats\x125\n" +
	"\x04list\x18\x01 \x03(\v2!.redbus.admincontrol.v1.RetryStatR\x04list\"\x96\x01\n" +
	"\tRetryStat\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x1b\n" +
	"\tall_count\x18\x03 \x01(\x05R\ballCount\x12!\n" +
	"\ffailed_count\x18\x04 \x01(\x05R\vfailedCount\x12\x1d\n" +
	"\n" +
	"last_error\x18\x05 \x01(\tR\tlastError\"B\n" +
	"\x14RestartFailedRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group2\xfd\x02\n" +
	"\x13AdminControlService\x12Z\n" +
	"\x10GetStateSnapshot\x12\x1d.redbus.admincontrol.v1.Empty\x1a%.redbus.admincontrol.v1.StateSnapshot\"\x00\x12T\n" +
	"\rGetTopicStats\x12\x1d.redbus.admincontrol.v1.Empty\x1a\".redbus.admincontrol.v1.TopicStats\"\x00\x12T\n" +
	"\rGetRetryStats\x12\x1d.redbus.admincontrol.v1.Empty\x1a\".redbus.admincontrol.v1.RetryStats\"\x00\x12^\n" +
	"\rRestartFailed\x12,.redbus.admincontrol.v1.RestartFailedRequest\x1a\x1d.redbus.admincontrol.v1.Empty\"\x00B6Z4github.com/prokraft/redbus/internal/api/admincontrolb\x06proto3"

var (
	file_internal_api_admincontrol_admincontrol_proto_rawDescOnce sync.Once
	file_internal_api_admincontrol_admincontrol_proto_rawDescData []byte
)

func file_internal_api_admincontrol_admincontrol_proto_rawDescGZIP() []byte {
	file_internal_api_admincontrol_admincontrol_proto_rawDescOnce.Do(func() {
		file_internal_api_admincontrol_admincontrol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_admincontrol_admincontrol_proto_rawDesc), len(file_internal_api_admincontrol_admincontrol_proto_rawDesc)))
	})
	return file_internal_api_admincontrol_admincontrol_proto_rawDescData
}

var file_internal_api_admincontrol_admincontrol_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_api_admincontrol_admincontrol_proto_goTypes = []any{
	(*Empty)(nil),                // 0: redbus.admincontrol.v1.Empty
	(*StateSnapshot)(nil),        // 1: redbus.admincontrol.v1.StateSnapshot
	(*TopicStats)(nil),           // 2: redbus.admincontrol.v1.TopicStats
	(*Topic)(nil),                // 3: redbus.admincontrol.v1.Topic
	(*Partition)(nil),            // 4: redbus.admincontrol.v1.Partition
	(*Group)(nil),                // 5: redbus.admincontrol.v1.Group
	(*GroupPartition)(nil),       // 6: redbus.admincontrol.v1.GroupPartition
	(*RetryStats)(nil),           // 7: redbus.admincontrol.v1.RetryStats
	(*RetryStat)(nil),            // 8: redbus.admincontrol.v1.RetryStat
	(*RestartFailedRequest)(nil), // 9: redbus.admincontrol.v1.RestartFailedRequest
}
var file_internal_api_admincontrol_admincontrol_proto_depIdxs = []int32{
	3, // 0: redbus.admincontrol.v1.TopicStats.list:type_name -> redbus.admincontrol.v1.Topic
	4, // 1: redbus.admincontrol.v1.Topic.partitions:type_name -> redbus.admincontrol.v1.Partition
	5, // 2: redbus.admincontrol.v1.Topic.groups:type_name -> redbus.admincontrol.v1.Group
	6, // 3: redbus.admincontrol.v1.Group.partitions:type_name -> redbus.admincontrol.v1.GroupPartition
	8, // 4: redbus.admincontrol.v1.RetryStats.list:type_name -> redbus.admincontrol.v1.RetryStat
	0, // 5: redbus.admincontrol.v1.AdminControlService.GetStateSnapshot:input_type -> redbus.admincontrol.v1.Empty
	0, // 6: redbus.admincontrol.v1.AdminControlService.GetTopicStats:input_type -> redbus.admincontrol.v1.Empty
	0, // 7: redbus.admincontrol.v1.AdminControlService.GetRetryStats:input_type -> redbus.admincontrol.v1.Empty
	9, // 8: redbus.admincontrol.v1.AdminControlService.RestartFailed:input_type -> redbus.admincontrol.v1.RestartFailedRequest
	1, // 9: redbus.admincontrol.v1.AdminControlService.GetStateSnapshot:output_type -> redbus.admincontrol.v1.StateSnapshot
	2, // 10: redbus.admincontrol.v1.AdminControlService.GetTopicStats:output_type -> redbus.admincontrol.v1.TopicStats
	7, // 11: redbus.admincontrol.v1.AdminControlService.GetRetryStats:output_type -> redbus.admincontrol.v1.RetryStats
	0, // 12: redbus.admincontrol.v1.AdminControlService.RestartFailed:output_type -> redbus.admincontrol.v1.Empty
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_api_admincontrol_admincontrol_proto_init() }
func file_internal_api_admincontrol_admincontrol_proto_init() {
	if File_internal_api_admincontrol_admincontrol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_admincontrol_admincontrol_proto_rawDesc), len(file_internal_api_admincontrol_admincontrol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_admincontrol_admincontrol_proto_goTypes,
		DependencyIndexes: file_internal_api_admincontrol_admincontrol_proto_depIdxs,
		MessageInfos:      file_internal_api_admincontrol_admincontrol_proto_msgTypes,
	}.Build()
	File_internal_api_admincontrol_admincontrol_proto = out.File
	file_internal_api_admincontrol_admincontrol_proto_goTypes = nil
	file_internal_api_admincontrol_admincontrol_proto_depIdxs = nil
}
