// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.0
// source: internal/api/admincontrol/admincontrol.proto

package admincontrol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminControlService_GetStateSnapshot_FullMethodName     = "/redbus.admincontrol.v1.AdminControlService/GetStateSnapshot"
	AdminControlService_GetTopicStats_FullMethodName        = "/redbus.admincontrol.v1.AdminControlService/GetTopicStats"
	AdminControlService_GetRetryStats_FullMethodName        = "/redbus.admincontrol.v1.AdminControlService/GetRetryStats"
	AdminControlService_RestartFailed_FullMethodName        = "/redbus.admincontrol.v1.AdminControlService/RestartFailed"
	AdminControlService_RestartFailedSince_FullMethodName   = "/redbus.admincontrol.v1.AdminControlService/RestartFailedSince"
	AdminControlService_RestartFailedByError_FullMethodName = "/redbus.admincontrol.v1.AdminControlService/RestartFailedByError"
	AdminControlService_DeleteFailedByError_FullMethodName  = "/redbus.admincontrol.v1.AdminControlService/DeleteFailedByError"
)

// AdminControlServiceClient is the client API for AdminControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminControlServiceClient interface {
	GetStateSnapshot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StateSnapshot, error)
	GetTopicStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TopicStats, error)
	GetRetryStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RetryStats, error)
	RestartFailed(ctx context.Context, in *RestartFailedRequest, opts ...grpc.CallOption) (*Empty, error)
	RestartFailedSince(ctx context.Context, in *RestartFailedSinceRequest, opts ...grpc.CallOption) (*Empty, error)
	RestartFailedByError(ctx context.Context, in *RestartFailedByErrorRequest, opts ...grpc.CallOption) (*Empty, error)
	DeleteFailedByError(ctx context.Context, in *DeleteFailedByErrorRequest, opts ...grpc.CallOption) (*Empty, error)
}

type adminControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminControlServiceClient(cc grpc.ClientConnInterface) AdminControlServiceClient {
	return &adminControlServiceClient{cc}
}

func (c *adminControlServiceClient) GetStateSnapshot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StateSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StateSnapshot)
	err := c.cc.Invoke(ctx, AdminControlService_GetStateSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminControlServiceClient) GetTopicStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TopicStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopicStats)
	err := c.cc.Invoke(ctx, AdminControlService_GetTopicStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminControlServiceClient) GetRetryStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RetryStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetryStats)
	err := c.cc.Invoke(ctx, AdminControlService_GetRetryStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminControlServiceClient) RestartFailed(ctx context.Context, in *RestartFailedRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminControlService_RestartFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminControlServiceClient) RestartFailedSince(ctx context.Context, in *RestartFailedSinceRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminControlService_RestartFailedSince_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminControlServiceClient) RestartFailedByError(ctx context.Context, in *RestartFailedByErrorRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminControlService_RestartFailedByError_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminControlServiceClient) DeleteFailedByError(ctx context.Context, in *DeleteFailedByErrorRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminControlService_DeleteFailedByError_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminControlServiceServer is the server API for AdminControlService service.
// All implementations should embed UnimplementedAdminControlServiceServer
// for forward compatibility.
type AdminControlServiceServer interface {
	GetStateSnapshot(context.Context, *Empty) (*StateSnapshot, error)
	GetTopicStats(context.Context, *Empty) (*TopicStats, error)
	GetRetryStats(context.Context, *Empty) (*RetryStats, error)
	RestartFailed(context.Context, *RestartFailedRequest) (*Empty, error)
	RestartFailedSince(context.Context, *RestartFailedSinceRequest) (*Empty, error)
	RestartFailedByError(context.Context, *RestartFailedByErrorRequest) (*Empty, error)
	DeleteFailedByError(context.Context, *DeleteFailedByErrorRequest) (*Empty, error)
}

// UnimplementedAdminControlServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminControlServiceServer struct{}

func (UnimplementedAdminControlServiceServer) GetStateSnapshot(context.Context, *Empty) (*StateSnapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStateSnapshot not implemented")
}
func (UnimplementedAdminControlServiceServer) GetTopicStats(context.Context, *Empty) (*TopicStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopicStats not implemented")
}
func (UnimplementedAdminControlServiceServer) GetRetryStats(context.Context, *Empty) (*RetryStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRetryStats not implemented")
}
func (UnimplementedAdminControlServiceServer) RestartFailed(context.Context, *RestartFailedRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestartFailed not implemented")
}
func (UnimplementedAdminControlServiceServer) RestartFailedSince(context.Context, *RestartFailedSinceRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestartFailedSince not implemented")
}
func (UnimplementedAdminControlServiceServer) RestartFailedByError(context.Context, *RestartFailedByErrorRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestartFailedByError not implemented")
}
func (UnimplementedAdminControlServiceServer) DeleteFailedByError(context.Context, *DeleteFailedByErrorRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFailedByError not implemented")
}
func (UnimplementedAdminControlServiceServer) testEmbeddedByValue() {}

// UnsafeAdminControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminControlServiceServer will
// result in compilation errors.
type UnsafeAdminControlServiceServer interface {
	mustEmbedUnimplementedAdminControlServiceServer()
}

func RegisterAdminControlServiceServer(s grpc.ServiceRegistrar, srv AdminControlServiceServer) {
	// If the following call pancis, it indicates UnimplementedAdminControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminControlService_ServiceDesc, srv)
}

func _AdminControlService_GetStateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminControlServiceServer).GetStateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminControlService_GetStateSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminControlServiceServer).GetStateSnapshot(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminControlService_GetTopicStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminControlServiceServer).GetTopicStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminControlService_GetTopicStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminControlServiceServer).GetTopicStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminControlService_GetRetryStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminControlServiceServer).GetRetryStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminControlService_GetRetryStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminControlServiceServer).GetRetryStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminControlService_RestartFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartFailedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminControlServiceServer).RestartFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminControlService_RestartFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminControlServiceServer).RestartFailed(ctx, req.(*RestartFailedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminControlService_RestartFailedSince_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartFailedSinceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminControlServiceServer).RestartFailedSince(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminControlService_RestartFailedSince_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminControlServiceServer).RestartFailedSince(ctx, req.(*RestartFailedSinceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminControlService_RestartFailedByError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartFailedByErrorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminControlServiceServer).RestartFailedByError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminControlService_RestartFailedByError_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminControlServiceServer).RestartFailedByError(ctx, req.(*RestartFailedByErrorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminControlService_DeleteFailedByError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFailedByErrorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminControlServiceServer).DeleteFailedByError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminControlService_DeleteFailedByError_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminControlServiceServer).DeleteFailedByError(ctx, req.(*DeleteFailedByErrorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminControlService_ServiceDesc is the grpc.ServiceDesc for AdminControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "redbus.admincontrol.v1.AdminControlService",
	HandlerType: (*AdminControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStateSnapshot",
			Handler:    _AdminControlService_GetStateSnapshot_Handler,
		},
		{
			MethodName: "GetTopicStats",
			Handler:    _AdminControlService_GetTopicStats_Handler,
		},
		{
			MethodName: "GetRetryStats",
			Handler:    _AdminControlService_GetRetryStats_Handler,
		},
		{
			MethodName: "RestartFailed",
			Handler:    _AdminControlService_RestartFailed_Handler,
		},
		{
			MethodName: "RestartFailedSince",
			Handler:    _AdminControlService_RestartFailedSince_Handler,
		},
		{
			MethodName: "RestartFailedByError",
			Handler:    _AdminControlService_RestartFailedByError_Handler,
		},
		{
			MethodName: "DeleteFailedByError",
			Handler:    _AdminControlService_DeleteFailedByError_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/api/admincontrol/admincontrol.proto",
}
