// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v7.36.0
// source: internal/api/admincontrol/admincontrol.proto

package admincontrol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_api_admincontrol_admincontrol_proto_rawDescGZIP(), []int{0}
}

type StateSnapshot struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConsumeTopicCount int32                  `protobuf:"varint,1,opt,name=consume_topic_count,json=consumeTopicCount,proto3" json:"consume_topic_count,omitempty"`
	ConsumerCount     int32                  `protobuf:"varint,2,opt,name=consumer_count,json=consumerCount,proto3" json:"consumer_count,omitempty"`
	RepeatAllCount    int32                  `protobuf:"varint,3,opt,name=repeat_all_count,json=repeatAllCount,proto3" json:"repeat_all_count,omitempty"`
	RepeatFailedCount int32                  `protobuf:"varint,4,opt,name=repeat_failed_count,json=repeatFailedCount,proto3" json:"repeat_failed_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StateSnapshot) Reset() {
	*x = StateSnapshot{}
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateSnapshot) ProtoMessage() {}

func (x *StateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateSnapshot.ProtoReflect.Descriptor instead.
func (*StateSnapshot) Descriptor() ([]byte, []int) {
	return file_internal_api_admincontrol_admincontrol_proto_rawDescGZIP(), []int{1}
}

func (x *StateSnapshot) GetConsumeTopicCount() int32 {
	if x != nil {
		return x.ConsumeTopicCount
	}
	return 0
}

func (x *StateSnapshot) GetConsumerCount() int32 {
	if x != nil {
		return x.ConsumerCount
	}
	return 0
}

func (x *StateSnapshot) GetRepeatAllCount() int32 {
	if x != nil {
		return x.RepeatAllCount
	}
	return 0
}

func (x *StateSnapshot) GetRepeatFailedCount() int32 {
	if x != nil {
		return x.RepeatFailedCount
	}
	return 0
}

type TopicStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Topic               `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicStats) Reset() {
	*x = TopicStats{}
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicStats) ProtoMessage() {}

func (x *TopicStats) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicStats.ProtoReflect.Descriptor instead.
func (*TopicStats) Descriptor() ([]byte, []int) {
	return file_internal_api_admincontrol_admincontrol_proto_rawDescGZIP(), []int{2}
}

func (x *TopicStats) GetList() []*Topic {
	if x != nil {
		return x.List
	}
	return nil
}

type Topic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Partitions    []*Partition           `protobuf:"bytes,2,rep,name=partitions,proto3" json:"partitions,omitempty"`
	Groups        []*Group               `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topic) Reset() {
	*x = Topic{}
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_internal_api_admincontrol_admincontrol_proto_rawDescGZIP(), []int{3}
}

func (x *Topic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Topic) GetPartitions() []*Partition {
	if x != nil {
		return x.Partitions
	}
	return nil
}

func (x *Topic) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type Partition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	FirstOffset   int64                  `protobuf:"varint,2,opt,name=first_offset,json=firstOffset,proto3" json:"first_offset,omitempty"`
	LastOffset    int64                  `protobuf:"varint,3,opt,name=last_offset,json=lastOffset,proto3" json:"last_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Partition) Reset() {
	*x = Partition{}
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Partition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Partition) ProtoMessage() {}

func (x *Partition) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Partition.ProtoReflect.Descriptor instead.
func (*Partition) Descriptor() ([]byte, []int) {
	return file_internal_api_admincontrol_admincontrol_proto_rawDescGZIP(), []int{4}
}

func (x *Partition) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Partition) GetFirstOffset() int64 {
	if x != nil {
		return x.FirstOffset
	}
	return 0
}

func (x *Partition) GetLastOffset() int64 {
	if x != nil {
		return x.LastOffset
	}
	return 0
}

type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Partitions    []*GroupPartition      `protobuf:"bytes,2,rep,name=partitions,proto3" json:"partitions,omitempty"`
	Consumers     []*Consumer            `protobuf:"bytes,3,rep,name=consumers,proto3" json:"consumers,omitempty"`
	KafkaGroupId  string                 `protobuf:"bytes,4,opt,name=kafka_group_id,json=kafkaGroupId,proto3" json:"kafka_group_id,omitempty"`
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_internal_api_admincontrol_admincontrol_proto_rawDescGZIP(), []int{5}
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetPartitions() []*GroupPartition {
	if x != nil {
		return x.Partitions
	}
	return nil
}

func (x *Group) GetConsumers() []*Consumer {
	if x != nil {
		return x.Consumers
	}
	return nil
}

func (x *Group) GetKafkaGroupId() string {
	if x != nil {
		return x.KafkaGroupId
	}
	return ""
}

func (x *Group) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Group) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Consumer struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State               string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Topic               string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Group               string                 `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	ConnectedAtUnixMs   int64                  `protobuf:"varint,5,opt,name=connected_at_unix_ms,json=connectedAtUnixMs,proto3" json:"connected_at_unix_ms,omitempty"`
	StateSinceUnixMs    int64                  `protobuf:"varint,6,opt,name=state_since_unix_ms,json=stateSinceUnixMs,proto3" json:"state_since_unix_ms,omitempty"`
	LastMessageAtUnixMs int64                  `protobuf:"varint,7,opt,name=last_message_at_unix_ms,json=lastMessageAtUnixMs,proto3" json:"last_message_at_unix_ms,omitempty"`
	MessagesProcessed   uint64                 `protobuf:"varint,8,opt,name=messages_processed,json=messagesProcessed,proto3" json:"messages_processed,omitempty"`
	ReconnectCount      uint64                 `protobuf:"varint,9,opt,name=reconnect_count,json=reconnectCount,proto3" json:"reconnect_count,omitempty"`
	LastError           string                 `protobuf:"bytes,10,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	RepeatStrategy      string                 `protobuf:"bytes,11,opt,name=repeat_strategy,json=repeatStrategy,proto3" json:"repeat_strategy,omitempty"`
	KafkaMemberId       string                 `protobuf:"bytes,12,opt,name=kafka_member_id,json=kafkaMemberId,proto3" json:"kafka_member_id,omitempty"`
	ClientHost          string                 `protobuf:"bytes,13,opt,name=client_host,json=clientHost,proto3" json:"client_host,omitempty"`
	Partitions          []*ConsumerPartition   `protobuf:"bytes,14,rep,name=partitions,proto3" json:"partitions,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Consumer) Reset() {
	*x = Consumer{}
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Consumer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consumer) ProtoMessage() {}

func (x *Consumer) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consumer.ProtoReflect.Descriptor instead.
func (*Consumer) Descriptor() ([]byte, []int) {
	return file_internal_api_admincontrol_admincontrol_proto_rawDescGZIP(), []int{6}
}

func (x *Consumer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Consumer) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Consumer) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Consumer) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Consumer) GetConnectedAtUnixMs() int64 {
	if x != nil {
		return x.ConnectedAtUnixMs
	}
	return 0
}

func (x *Consumer) GetStateSinceUnixMs() int64 {
	if x != nil {
		return x.StateSinceUnixMs
	}
	return 0
}

func (x *Consumer) GetLastMessageAtUnixMs() int64 {
	if x != nil {
		return x.LastMessageAtUnixMs
	}
	return 0
}

func (x *Consumer) GetMessagesProcessed() uint64 {
	if x != nil {
		return x.MessagesProcessed
	}
	return 0
}

func (x *Consumer) GetReconnectCount() uint64 {
	if x != nil {
		return x.ReconnectCount
	}
	return 0
}

func (x *Consumer) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *Consumer) GetRepeatStrategy() string {
	if x != nil {
		return x.RepeatStrategy
	}
	return ""
}

func (x *Consumer) GetKafkaMemberId() string {
	if x != nil {
		return x.KafkaMemberId
	}
	return ""
}

func (x *Consumer) GetClientHost() string {
	if x != nil {
		return x.ClientHost
	}
	return ""
}

func (x *Consumer) GetPartitions() []*ConsumerPartition {
	if x != nil {
		return x.Partitions
	}
	return nil
}

type ConsumerPartition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	GroupOffset   int64                  `protobuf:"varint,2,opt,name=group_offset,json=groupOffset,proto3" json:"group_offset,omitempty"`
	LastOffset    int64                  `protobuf:"varint,3,opt,name=last_offset,json=lastOffset,proto3" json:"last_offset,omitempty"`
	Lag           int64                  `protobuf:"varint,4,opt,name=lag,proto3" json:"lag,omitempty"`
	Committed     bool                   `protobuf:"varint,5,opt,name=committed,proto3" json:"committed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumerPartition) Reset() {
	*x = ConsumerPartition{}
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerPartition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerPartition) ProtoMessage() {}

func (x *ConsumerPartition) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerPartition.ProtoReflect.Descriptor instead.
func (*ConsumerPartition) Descriptor() ([]byte, []int) {
	return file_internal_api_admincontrol_admincontrol_proto_rawDescGZIP(), []int{7}
}

func (x *ConsumerPartition) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *ConsumerPartition) GetGroupOffset() int64 {
	if x != nil {
		return x.GroupOffset
	}
	return 0
}

func (x *ConsumerPartition) GetLastOffset() int64 {
	if x != nil {
		return x.LastOffset
	}
	return 0
}

func (x *ConsumerPartition) GetLag() int64 {
	if x != nil {
		return x.Lag
	}
	return 0
}

func (x *ConsumerPartition) GetCommitted() bool {
	if x != nil {
		return x.Committed
	}
	return false
}

type GroupPartition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	ConsumerId    string                 `protobuf:"bytes,3,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	ConsumerState string                 `protobuf:"bytes,4,opt,name=consumer_state,json=consumerState,proto3" json:"consumer_state,omitempty"`
	FirstOffset   int64                  `protobuf:"varint,5,opt,name=first_offset,json=firstOffset,proto3" json:"first_offset,omitempty"`
	LastOffset    int64                  `protobuf:"varint,6,opt,name=last_offset,json=lastOffset,proto3" json:"last_offset,omitempty"`
	Lag           int64                  `protobuf:"varint,7,opt,name=lag,proto3" json:"lag,omitempty"`
	Committed     bool                   `protobuf:"varint,8,opt,name=committed,proto3" json:"committed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupPartition) Reset() {
	*x = GroupPartition{}
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupPartition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupPartition) ProtoMessage() {}

func (x *GroupPartition) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupPartition.ProtoReflect.Descriptor instead.
func (*GroupPartition) Descriptor() ([]byte, []int) {
	return file_internal_api_admincontrol_admincontrol_proto_rawDescGZIP(), []int{8}
}

func (x *GroupPartition) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *GroupPartition) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GroupPartition) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *GroupPartition) GetConsumerState() string {
	if x != nil {
		return x.ConsumerState
	}
	return ""
}

func (x *GroupPartition) GetFirstOffset() int64 {
	if x != nil {
		return x.FirstOffset
	}
	return 0
}

func (x *GroupPartition) GetLastOffset() int64 {
	if x != nil {
		return x.LastOffset
	}
	return 0
}

func (x *GroupPartition) GetLag() int64 {
	if x != nil {
		return x.Lag
	}
	return 0
}

func (x *GroupPartition) GetCommitted() bool {
	if x != nil {
		return x.Committed
	}
	return false
}

type RetryStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*RetryStat           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryStats) Reset() {
	*x = RetryStats{}
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryStats) ProtoMessage() {}

func (x *RetryStats) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryStats.ProtoReflect.Descriptor instead.
func (*RetryStats) Descriptor() ([]byte, []int) {
	return file_internal_api_admincontrol_admincontrol_proto_rawDescGZIP(), []int{9}
}

func (x *RetryStats) GetList() []*RetryStat {
	if x != nil {
		return x.List
	}
	return nil
}

type RetryStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	AllCount      int32                  `protobuf:"varint,3,opt,name=all_count,json=allCount,proto3" json:"all_count,omitempty"`
	FailedCount   int32                  `protobuf:"varint,4,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	LastError     string                 `protobuf:"bytes,5,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	Errors        []*RetryErrorStat      `protobuf:"bytes,6,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryStat) Reset() {
	*x = RetryStat{}
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryStat) ProtoMessage() {}

func (x *RetryStat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryStat.ProtoReflect.Descriptor instead.
func (*RetryStat) Descriptor() ([]byte, []int) {
	return file_internal_api_admincontrol_admincontrol_proto_rawDescGZIP(), []int{10}
}

func (x *RetryStat) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *RetryStat) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *RetryStat) GetAllCount() int32 {
	if x != nil {
		return x.AllCount
	}
	return 0
}

func (x *RetryStat) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *RetryStat) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *RetryStat) GetErrors() []*RetryErrorStat {
	if x != nil {
		return x.Errors
	}
	return nil
}

type RetryErrorStat struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Error               string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	FailedCount         int32                  `protobuf:"varint,2,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	FirstFailedAtUnixMs int64                  `protobuf:"varint,3,opt,name=first_failed_at_unix_ms,json=firstFailedAtUnixMs,proto3" json:"first_failed_at_unix_ms,omitempty"`
	LastFailedAtUnixMs  int64                  `protobuf:"varint,4,opt,name=last_failed_at_unix_ms,json=lastFailedAtUnixMs,proto3" json:"last_failed_at_unix_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RetryErrorStat) Reset() {
	*x = RetryErrorStat{}
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryErrorStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryErrorStat) ProtoMessage() {}

func (x *RetryErrorStat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryErrorStat.ProtoReflect.Descriptor instead.
func (*RetryErrorStat) Descriptor() ([]byte, []int) {
	return file_internal_api_admincontrol_admincontrol_proto_rawDescGZIP(), []int{11}
}

func (x *RetryErrorStat) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RetryErrorStat) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *RetryErrorStat) GetFirstFailedAtUnixMs() int64 {
	if x != nil {
		return x.FirstFailedAtUnixMs
	}
	return 0
}

func (x *RetryErrorStat) GetLastFailedAtUnixMs() int64 {
	if x != nil {
		return x.LastFailedAtUnixMs
	}
	return 0
}

type RestartFailedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartFailedRequest) Reset() {
	*x = RestartFailedRequest{}
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartFailedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartFailedRequest) ProtoMessage() {}

func (x *RestartFailedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartFailedRequest.ProtoReflect.Descriptor instead.
func (*RestartFailedRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_admincontrol_admincontrol_proto_rawDescGZIP(), []int{12}
}

func (x *RestartFailedRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *RestartFailedRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type RestartFailedSinceRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Topic           string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Group           string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	LookbackSeconds int64                  `protobuf:"varint,3,opt,name=lookback_seconds,json=lookbackSeconds,proto3" json:"lookback_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RestartFailedSinceRequest) Reset() {
	*x = RestartFailedSinceRequest{}
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartFailedSinceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartFailedSinceRequest) ProtoMessage() {}

func (x *RestartFailedSinceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartFailedSinceRequest.ProtoReflect.Descriptor instead.
func (*RestartFailedSinceRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_admincontrol_admincontrol_proto_rawDescGZIP(), []int{13}
}

func (x *RestartFailedSinceRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *RestartFailedSinceRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *RestartFailedSinceRequest) GetLookbackSeconds() int64 {
	if x != nil {
		return x.LookbackSeconds
	}
	return 0
}

type RestartFailedByErrorRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Topic           string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Group           string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Error           string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	LookbackSeconds int64                  `protobuf:"varint,4,opt,name=lookback_seconds,json=lookbackSeconds,proto3" json:"lookback_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RestartFailedByErrorRequest) Reset() {
	*x = RestartFailedByErrorRequest{}
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartFailedByErrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartFailedByErrorRequest) ProtoMessage() {}

func (x *RestartFailedByErrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartFailedByErrorRequest.ProtoReflect.Descriptor instead.
func (*RestartFailedByErrorRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_admincontrol_admincontrol_proto_rawDescGZIP(), []int{14}
}

func (x *RestartFailedByErrorRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *RestartFailedByErrorRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *RestartFailedByErrorRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RestartFailedByErrorRequest) GetLookbackSeconds() int64 {
	if x != nil {
		return x.LookbackSeconds
	}
	return 0
}

type DeleteFailedByErrorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFailedByErrorRequest) Reset() {
	*x = DeleteFailedByErrorRequest{}
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFailedByErrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFailedByErrorRequest) ProtoMessage() {}

func (x *DeleteFailedByErrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_admincontrol_admincontrol_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFailedByErrorRequest.ProtoReflect.Descriptor instead.
func (*DeleteFailedByErrorRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_admincontrol_admincontrol_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteFailedByErrorRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *DeleteFailedByErrorRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *DeleteFailedByErrorRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_api_admincontrol_admincontrol_proto protoreflect.FileDescriptor

const file_internal_api_admincontrol_admincontrol_proto_rawDesc = "" +
	"\n" +
	",internal/api/admincontrol/admincontrol.proto\x12\x16redbus.admincontrol.v1\"\a\n" +
	"\x05Empty\"\xc0\x01\n" +
	"\rStateSnapshot\x12.\n" +
	"\x13consume_topic_count\x18\x01 \x01(\x05R\x11consumeTopicCount\x12%\n" +
	"\x0econsumer_count\x18\x02 \x01(\x05R\rconsumerCount\x12(\n" +
	"\x10repeat_all_count\x18\x03 \x01(\x05R\x0erepeatAllCount\x12.\n" +
	"\x13repeat_failed_count\x18\x04 \x01(\x05R\x11repeatFailedCount\"?\n" +
	"\n" +
	"TopicStats\x121\n" +
	"\x04list\x18\x01 \x03(\v2\x1d.redbus.admincontrol.v1.TopicR\x04list\"\x95\x01\n" +
	"\x05Topic\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12A\n" +
	"\n" +
	"partitions\x18\x02 \x03(\v2!.redbus.admincontrol.v1.PartitionR\n" +
	"partitions\x125\n" +
	"\x06groups\x18\x03 \x03(\v2\x1d.redbus.admincontrol.v1.GroupR\x06groups\"g\n" +
	"\tPartition\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x12!\n" +
	"\ffirst_offset\x18\x02 \x01(\x03R\vfirstOffset\x12\x1f\n" +
	"\vlast_offset\x18\x03 \x01(\x03R\n" +
	"lastOffset\"\xf5\x01\n" +
	"\x05Group\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12F\n" +
	"\n" +
	"partitions\x18\x02 \x03(\v2&.redbus.admincontrol.v1.GroupPartitionR\n" +
	"partitions\x12>\n" +
	"\tconsumers\x18\x03 \x03(\v2 .redbus.admincontrol.v1.ConsumerR\tconsumers\x12$\n" +
	"\x0ekafka_group_id\x18\x04 \x01(\tR\fkafkaGroupId\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\xa6\x04\n" +
	"\bConsumer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12\x14\n" +
	"\x05group\x18\x04 \x01(\tR\x05group\x12/\n" +
	"\x14connected_at_unix_ms\x18\x05 \x01(\x03R\x11connectedAtUnixMs\x12-\n" +
	"\x13state_since_unix_ms\x18\x06 \x01(\x03R\x10stateSinceUnixMs\x124\n" +
	"\x17last_message_at_unix_ms\x18\a \x01(\x03R\x13lastMessageAtUnixMs\x12-\n" +
	"\x12messages_processed\x18\b \x01(\x04R\x11messagesProcessed\x12'\n" +
	"\x0freconnect_count\x18\t \x01(\x04R\x0ereconnectCount\x12\x1d\n" +
	"\n" +
	"last_error\x18\n" +
	" \x01(\tR\tlastError\x12'\n" +
	"\x0frepeat_strategy\x18\v \x01(\tR\x0erepeatStrategy\x12&\n" +
	"\x0fkafka_member_id\x18\f \x01(\tR\rkafkaMemberId\x12\x1f\n" +
	"\vclient_host\x18\r \x01(\tR\n" +
	"clientHost\x12I\n" +
	"\n" +
	"partitions\x18\x0e \x03(\v2).redbus.admincontrol.v1.ConsumerPartitionR\n" +
	"partitions\"\x9f\x01\n" +
	"\x11ConsumerPartition\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x12!\n" +
	"\fgroup_offset\x18\x02 \x01(\x03R\vgroupOffset\x12\x1f\n" +
	"\vlast_offset\x18\x03 \x01(\x03R\n" +
	"lastOffset\x12\x10\n" +
	"\x03lag\x18\x04 \x01(\x03R\x03lag\x12\x1c\n" +
	"\tcommitted\x18\x05 \x01(\bR\tcommitted\"\xfc\x01\n" +
	"\x0eGroupPartition\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x1f\n" +
	"\vconsumer_id\x18\x03 \x01(\tR\n" +
	"consumerId\x12%\n" +
	"\x0econsumer_state\x18\x04 \x01(\tR\rconsumerState\x12!\n" +
	"\ffirst_offset\x18\x05 \x01(\x03R\vfirstOffset\x12\x1f\n" +
	"\vlast_offset\x18\x06 \x01(\x03R\n" +
	"lastOffset\x12\x10\n" +
	"\x03lag\x18\a \x01(\x03R\x03lag\x12\x1c\n" +
	"\tcommitted\x18\b \x01(\bR\tcommitted\"C\n" +
	"\n" +
	"RetryStats\x125\n" +
	"\x04list\x18\x01 \x03(\v2!.redbus.admincontrol.v1.RetryStatR\x04list\"\xd6\x01\n" +
	"\tRetryStat\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x1b\n" +
	"\tall_count\x18\x03 \x01(\x05R\ballCount\x12!\n" +
	"\ffailed_count\x18\x04 \x01(\x05R\vfailedCount\x12\x1d\n" +
	"\n" +
	"last_error\x18\x05 \x01(\tR\tlastError\x12>\n" +
	"\x06errors\x18\x06 \x03(\v2&.redbus.admincontrol.v1.RetryErrorStatR\x06errors\"\xb3\x01\n" +
	"\x0eRetryErrorStat\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12!\n" +
	"\ffailed_count\x18\x02 \x01(\x05R\vfailedCount\x124\n" +
	"\x17first_failed_at_unix_ms\x18\x03 \x01(\x03R\x13firstFailedAtUnixMs\x122\n" +
	"\x16last_failed_at_unix_ms\x18\x04 \x01(\x03R\x12lastFailedAtUnixMs\"B\n" +
	"\x14RestartFailedRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\"r\n" +
	"\x19RestartFailedSinceRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12)\n" +
	"\x10lookback_seconds\x18\x03 \x01(\x03R\x0flookbackSeconds\"\x8a\x01\n" +
	"\x1bRestartFailedByErrorRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12)\n" +
	"\x10lookback_seconds\x18\x04 \x01(\x03R\x0flookbackSeconds\"^\n" +
	"\x1aDeleteFailedByErrorRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\xc1\x05\n" +
	"\x13AdminControlService\x12Z\n" +
	"\x10GetStateSnapshot\x12\x1d.redbus.admincontrol.v1.Empty\x1a%.redbus.admincontrol.v1.StateSnapshot\"\x00\x12T\n" +
	"\rGetTopicStats\x12\x1d.redbus.admincontrol.v1.Empty\x1a\".redbus.admincontrol.v1.TopicStats\"\x00\x12T\n" +
	"\rGetRetryStats\x12\x1d.redbus.admincontrol.v1.Empty\x1a\".redbus.admincontrol.v1.RetryStats\"\x00\x12^\n" +
	"\rRestartFailed\x12,.redbus.admincontrol.v1.RestartFailedRequest\x1a\x1d.redbus.admincontrol.v1.Empty\"\x00\x12h\n" +
	"\x12RestartFailedSince\x121.redbus.admincontrol.v1.RestartFailedSinceRequest\x1a\x1d.redbus.admincontrol.v1.Empty\"\x00\x12l\n" +
	"\x14RestartFailedByError\x123.redbus.admincontrol.v1.RestartFailedByErrorRequest\x1a\x1d.redbus.admincontrol.v1.Empty\"\x00\x12j\n" +
	"\x13DeleteFailedByError\x122.redbus.admincontrol.v1.DeleteFailedByErrorRequest\x1a\x1d.redbus.admincontrol.v1.Empty\"\x00B6Z4github.com/prokraft/redbus/internal/api/admincontrolb\x06proto3"

var (
	file_internal_api_admincontrol_admincontrol_proto_rawDescOnce sync.Once
	file_internal_api_admincontrol_admincontrol_proto_rawDescData []byte
)

func file_internal_api_admincontrol_admincontrol_proto_rawDescGZIP() []byte {
	file_internal_api_admincontrol_admincontrol_proto_rawDescOnce.Do(func() {
		file_internal_api_admincontrol_admincontrol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_admincontrol_admincontrol_proto_rawDesc), len(file_internal_api_admincontrol_admincontrol_proto_rawDesc)))
	})
	return file_internal_api_admincontrol_admincontrol_proto_rawDescData
}

var file_internal_api_admincontrol_admincontrol_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_internal_api_admincontrol_admincontrol_proto_goTypes = []any{
	(*Empty)(nil),                       // 0: redbus.admincontrol.v1.Empty
	(*StateSnapshot)(nil),               // 1: redbus.admincontrol.v1.StateSnapshot
	(*TopicStats)(nil),                  // 2: redbus.admincontrol.v1.TopicStats
	(*Topic)(nil),                       // 3: redbus.admincontrol.v1.Topic
	(*Partition)(nil),                   // 4: redbus.admincontrol.v1.Partition
	(*Group)(nil),                       // 5: redbus.admincontrol.v1.Group
	(*Consumer)(nil),                    // 6: redbus.admincontrol.v1.Consumer
	(*ConsumerPartition)(nil),           // 7: redbus.admincontrol.v1.ConsumerPartition
	(*GroupPartition)(nil),              // 8: redbus.admincontrol.v1.GroupPartition
	(*RetryStats)(nil),                  // 9: redbus.admincontrol.v1.RetryStats
	(*RetryStat)(nil),                   // 10: redbus.admincontrol.v1.RetryStat
	(*RetryErrorStat)(nil),              // 11: redbus.admincontrol.v1.RetryErrorStat
	(*RestartFailedRequest)(nil),        // 12: redbus.admincontrol.v1.RestartFailedRequest
	(*RestartFailedSinceRequest)(nil),   // 13: redbus.admincontrol.v1.RestartFailedSinceRequest
	(*RestartFailedByErrorRequest)(nil), // 14: redbus.admincontrol.v1.RestartFailedByErrorRequest
	(*DeleteFailedByErrorRequest)(nil),  // 15: redbus.admincontrol.v1.DeleteFailedByErrorRequest
}
var file_internal_api_admincontrol_admincontrol_proto_depIdxs = []int32{
	3,  // 0: redbus.admincontrol.v1.TopicStats.list:type_name -> redbus.admincontrol.v1.Topic
	4,  // 1: redbus.admincontrol.v1.Topic.partitions:type_name -> redbus.admincontrol.v1.Partition
	5,  // 2: redbus.admincontrol.v1.Topic.groups:type_name -> redbus.admincontrol.v1.Group
	8,  // 3: redbus.admincontrol.v1.Group.partitions:type_name -> redbus.admincontrol.v1.GroupPartition
	6,  // 4: redbus.admincontrol.v1.Group.consumers:type_name -> redbus.admincontrol.v1.Consumer
	7,  // 5: redbus.admincontrol.v1.Consumer.partitions:type_name -> redbus.admincontrol.v1.ConsumerPartition
	10, // 6: redbus.admincontrol.v1.RetryStats.list:type_name -> redbus.admincontrol.v1.RetryStat
	11, // 7: redbus.admincontrol.v1.RetryStat.errors:type_name -> redbus.admincontrol.v1.RetryErrorStat
	0,  // 8: redbus.admincontrol.v1.AdminControlService.GetStateSnapshot:input_type -> redbus.admincontrol.v1.Empty
	0,  // 9: redbus.admincontrol.v1.AdminControlService.GetTopicStats:input_type -> redbus.admincontrol.v1.Empty
	0,  // 10: redbus.admincontrol.v1.AdminControlService.GetRetryStats:input_type -> redbus.admincontrol.v1.Empty
	12, // 11: redbus.admincontrol.v1.AdminControlService.RestartFailed:input_type -> redbus.admincontrol.v1.RestartFailedRequest
	13, // 12: redbus.admincontrol.v1.AdminControlService.RestartFailedSince:input_type -> redbus.admincontrol.v1.RestartFailedSinceRequest
	14, // 13: redbus.admincontrol.v1.AdminControlService.RestartFailedByError:input_type -> redbus.admincontrol.v1.RestartFailedByErrorRequest
	15, // 14: redbus.admincontrol.v1.AdminControlService.DeleteFailedByError:input_type -> redbus.admincontrol.v1.DeleteFailedByErrorRequest
	1,  // 15: redbus.admincontrol.v1.AdminControlService.GetStateSnapshot:output_type -> redbus.admincontrol.v1.StateSnapshot
	2,  // 16: redbus.admincontrol.v1.AdminControlService.GetTopicStats:output_type -> redbus.admincontrol.v1.TopicStats
	9,  // 17: redbus.admincontrol.v1.AdminControlService.GetRetryStats:output_type -> redbus.admincontrol.v1.RetryStats
	0,  // 18: redbus.admincontrol.v1.AdminControlService.RestartFailed:output_type -> redbus.admincontrol.v1.Empty
	0,  // 19: redbus.admincontrol.v1.AdminControlService.RestartFailedSince:output_type -> redbus.admincontrol.v1.Empty
	0,  // 20: redbus.admincontrol.v1.AdminControlService.RestartFailedByError:output_type -> redbus.admincontrol.v1.Empty
	0,  // 21: redbus.admincontrol.v1.AdminControlService.DeleteFailedByError:output_type -> redbus.admincontrol.v1.Empty
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_internal_api_admincontrol_admincontrol_proto_init() }
func file_internal_api_admincontrol_admincontrol_proto_init() {
	if File_internal_api_admincontrol_admincontrol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_admincontrol_admincontrol_proto_rawDesc), len(file_internal_api_admincontrol_admincontrol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_admincontrol_admincontrol_proto_goTypes,
		DependencyIndexes: file_internal_api_admincontrol_admincontrol_proto_depIdxs,
		MessageInfos:      file_internal_api_admincontrol_admincontrol_proto_msgTypes,
	}.Build()
	File_internal_api_admincontrol_admincontrol_proto = out.File
	file_internal_api_admincontrol_admincontrol_proto_goTypes = nil
	file_internal_api_admincontrol_admincontrol_proto_depIdxs = nil
}
