// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProduceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Topic          string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Key            string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Message        []byte                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotencyKey,proto3" json:"idempotencyKey,omitempty"`
	Timestamp      string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version        int64                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProduceRequest) Reset() {
	*x = ProduceRequest{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceRequest) ProtoMessage() {}

func (x *ProduceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceRequest.ProtoReflect.Descriptor instead.
func (*ProduceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *ProduceRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ProduceRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ProduceRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ProduceRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ProduceRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ProduceRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ProduceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceResponse) Reset() {
	*x = ProduceResponse{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceResponse) ProtoMessage() {}

func (x *ProduceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceResponse.ProtoReflect.Descriptor instead.
func (*ProduceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *ProduceResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ConsumeRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Connect       *ConsumeRequest_Connect  `protobuf:"bytes,1,opt,name=connect,proto3" json:"connect,omitempty"`
	ResultList    []*ConsumeRequest_Result `protobuf:"bytes,2,rep,name=resultList,proto3" json:"resultList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeRequest) Reset() {
	*x = ConsumeRequest{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeRequest) ProtoMessage() {}

func (x *ConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeRequest.ProtoReflect.Descriptor instead.
func (*ConsumeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *ConsumeRequest) GetConnect() *ConsumeRequest_Connect {
	if x != nil {
		return x.Connect
	}
	return nil
}

func (x *ConsumeRequest) GetResultList() []*ConsumeRequest_Result {
	if x != nil {
		return x.ResultList
	}
	return nil
}

type ConsumeResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Connect       *ConsumeResponse_Connect   `protobuf:"bytes,1,opt,name=connect,proto3" json:"connect,omitempty"`
	MessageList   []*ConsumeResponse_Message `protobuf:"bytes,2,rep,name=messageList,proto3" json:"messageList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeResponse) Reset() {
	*x = ConsumeResponse{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeResponse) ProtoMessage() {}

func (x *ConsumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeResponse.ProtoReflect.Descriptor instead.
func (*ConsumeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *ConsumeResponse) GetConnect() *ConsumeResponse_Connect {
	if x != nil {
		return x.Connect
	}
	return nil
}

func (x *ConsumeResponse) GetMessageList() []*ConsumeResponse_Message {
	if x != nil {
		return x.MessageList
	}
	return nil
}

type ConsumeRequest_Connect struct {
	state          protoimpl.MessageState                 `protogen:"open.v1"`
	Id             string                                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic          string                                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Group          string                                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	RepeatStrategy *ConsumeRequest_Connect_RepeatStrategy `protobuf:"bytes,4,opt,name=repeatStrategy,proto3" json:"repeatStrategy,omitempty"`
	BatchSize      int32                                  `protobuf:"varint,5,opt,name=batchSize,proto3" json:"batchSize,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConsumeRequest_Connect) Reset() {
	*x = ConsumeRequest_Connect{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeRequest_Connect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeRequest_Connect) ProtoMessage() {}

func (x *ConsumeRequest_Connect) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeRequest_Connect.ProtoReflect.Descriptor instead.
func (*ConsumeRequest_Connect) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ConsumeRequest_Connect) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConsumeRequest_Connect) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ConsumeRequest_Connect) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ConsumeRequest_Connect) GetRepeatStrategy() *ConsumeRequest_Connect_RepeatStrategy {
	if x != nil {
		return x.RepeatStrategy
	}
	return nil
}

func (x *ConsumeRequest_Connect) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

type ConsumeRequest_Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeRequest_Result) Reset() {
	*x = ConsumeRequest_Result{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeRequest_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeRequest_Result) ProtoMessage() {}

func (x *ConsumeRequest_Result) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeRequest_Result.ProtoReflect.Descriptor instead.
func (*ConsumeRequest_Result) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2, 1}
}

func (x *ConsumeRequest_Result) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConsumeRequest_Result) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ConsumeRequest_Result) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConsumeRequest_Connect_RepeatStrategy struct {
	state             protoimpl.MessageState                                   `protogen:"open.v1"`
	MaxAttempts       int32                                                    `protobuf:"varint,1,opt,name=maxAttempts,proto3" json:"maxAttempts,omitempty"`
	EvenConfig        *ConsumeRequest_Connect_RepeatStrategy_EvenConfig        `protobuf:"bytes,2,opt,name=evenConfig,proto3" json:"evenConfig,omitempty"`
	ProgressiveConfig *ConsumeRequest_Connect_RepeatStrategy_ProgressiveConfig `protobuf:"bytes,3,opt,name=progressiveConfig,proto3" json:"progressiveConfig,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConsumeRequest_Connect_RepeatStrategy) Reset() {
	*x = ConsumeRequest_Connect_RepeatStrategy{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeRequest_Connect_RepeatStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeRequest_Connect_RepeatStrategy) ProtoMessage() {}

func (x *ConsumeRequest_Connect_RepeatStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeRequest_Connect_RepeatStrategy.ProtoReflect.Descriptor instead.
func (*ConsumeRequest_Connect_RepeatStrategy) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *ConsumeRequest_Connect_RepeatStrategy) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *ConsumeRequest_Connect_RepeatStrategy) GetEvenConfig() *ConsumeRequest_Connect_RepeatStrategy_EvenConfig {
	if x != nil {
		return x.EvenConfig
	}
	return nil
}

func (x *ConsumeRequest_Connect_RepeatStrategy) GetProgressiveConfig() *ConsumeRequest_Connect_RepeatStrategy_ProgressiveConfig {
	if x != nil {
		return x.ProgressiveConfig
	}
	return nil
}

type ConsumeRequest_Connect_RepeatStrategy_EvenConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IntervalSec   int32                  `protobuf:"varint,1,opt,name=intervalSec,proto3" json:"intervalSec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeRequest_Connect_RepeatStrategy_EvenConfig) Reset() {
	*x = ConsumeRequest_Connect_RepeatStrategy_EvenConfig{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeRequest_Connect_RepeatStrategy_EvenConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeRequest_Connect_RepeatStrategy_EvenConfig) ProtoMessage() {}

func (x *ConsumeRequest_Connect_RepeatStrategy_EvenConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeRequest_Connect_RepeatStrategy_EvenConfig.ProtoReflect.Descriptor instead.
func (*ConsumeRequest_Connect_RepeatStrategy_EvenConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2, 0, 0, 0}
}

func (x *ConsumeRequest_Connect_RepeatStrategy_EvenConfig) GetIntervalSec() int32 {
	if x != nil {
		return x.IntervalSec
	}
	return 0
}

type ConsumeRequest_Connect_RepeatStrategy_ProgressiveConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IntervalSec   int32                  `protobuf:"varint,1,opt,name=intervalSec,proto3" json:"intervalSec,omitempty"`
	Multiplier    float32                `protobuf:"fixed32,2,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeRequest_Connect_RepeatStrategy_ProgressiveConfig) Reset() {
	*x = ConsumeRequest_Connect_RepeatStrategy_ProgressiveConfig{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeRequest_Connect_RepeatStrategy_ProgressiveConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeRequest_Connect_RepeatStrategy_ProgressiveConfig) ProtoMessage() {}

func (x *ConsumeRequest_Connect_RepeatStrategy_ProgressiveConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeRequest_Connect_RepeatStrategy_ProgressiveConfig.ProtoReflect.Descriptor instead.
func (*ConsumeRequest_Connect_RepeatStrategy_ProgressiveConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2, 0, 0, 1}
}

func (x *ConsumeRequest_Connect_RepeatStrategy_ProgressiveConfig) GetIntervalSec() int32 {
	if x != nil {
		return x.IntervalSec
	}
	return 0
}

func (x *ConsumeRequest_Connect_RepeatStrategy_ProgressiveConfig) GetMultiplier() float32 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

type ConsumeResponse_Connect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeResponse_Connect) Reset() {
	*x = ConsumeResponse_Connect{}
	mi := &file_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeResponse_Connect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeResponse_Connect) ProtoMessage() {}

func (x *ConsumeResponse_Connect) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeResponse_Connect.ProtoReflect.Descriptor instead.
func (*ConsumeResponse_Connect) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ConsumeResponse_Connect) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ConsumeResponse_Connect) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConsumeResponse_Message struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data           []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotencyKey,proto3" json:"idempotencyKey,omitempty"`
	Timestamp      string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version        int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConsumeResponse_Message) Reset() {
	*x = ConsumeResponse_Message{}
	mi := &file_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeResponse_Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeResponse_Message) ProtoMessage() {}

func (x *ConsumeResponse_Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeResponse_Message.ProtoReflect.Descriptor instead.
func (*ConsumeResponse_Message) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3, 1}
}

func (x *ConsumeResponse_Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConsumeResponse_Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ConsumeResponse_Message) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ConsumeResponse_Message) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ConsumeResponse_Message) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\x0fsergiusd.redbus\"\xb2\x01\n" +
	"\x0eProduceRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x18\n" +
	"\amessage\x18\x03 \x01(\fR\amessage\x12&\n" +
	"\x0eidempotencyKey\x18\x04 \x01(\tR\x0eidempotencyKey\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x03R\aversion\"!\n" +
	"\x0fProduceResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\xbc\x06\n" +
	"\x0eConsumeRequest\x12A\n" +
	"\aconnect\x18\x01 \x01(\v2'.sergiusd.redbus.ConsumeRequest.ConnectR\aconnect\x12F\n" +
	"\n" +
	"resultList\x18\x02 \x03(\v2&.sergiusd.redbus.ConsumeRequest.ResultR\n" +
	"resultList\x1a\xda\x04\n" +
	"\aConnect\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\x12^\n" +
	"\x0erepeatStrategy\x18\x04 \x01(\v26.sergiusd.redbus.ConsumeRequest.Connect.RepeatStrategyR\x0erepeatStrategy\x12\x1c\n" +
	"\tbatchSize\x18\x05 \x01(\x05R\tbatchSize\x1a\x94\x03\n" +
	"\x0eRepeatStrategy\x12 \n" +
	"\vmaxAttempts\x18\x01 \x01(\x05R\vmaxAttempts\x12a\n" +
	"\n" +
	"evenConfig\x18\x02 \x01(\v2A.sergiusd.redbus.ConsumeRequest.Connect.RepeatStrategy.EvenConfigR\n" +
	"evenConfig\x12v\n" +
	"\x11progressiveConfig\x18\x03 \x01(\v2H.sergiusd.redbus.ConsumeRequest.Connect.RepeatStrategy.ProgressiveConfigR\x11progressiveConfig\x1a.\n" +
	"\n" +
	"EvenConfig\x12 \n" +
	"\vintervalSec\x18\x01 \x01(\x05R\vintervalSec\x1aU\n" +
	"\x11ProgressiveConfig\x12 \n" +
	"\vintervalSec\x18\x01 \x01(\x05R\vintervalSec\x12\x1e\n" +
	"\n" +
	"multiplier\x18\x02 \x01(\x02R\n" +
	"multiplier\x1aB\n" +
	"\x06Result\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xe6\x02\n" +
	"\x0fConsumeResponse\x12B\n" +
	"\aconnect\x18\x01 \x01(\v2(.sergiusd.redbus.ConsumeResponse.ConnectR\aconnect\x12J\n" +
	"\vmessageList\x18\x02 \x03(\v2(.sergiusd.redbus.ConsumeResponse.MessageR\vmessageList\x1a3\n" +
	"\aConnect\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x1a\x8d\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12&\n" +
	"\x0eidempotencyKey\x18\x03 \x01(\tR\x0eidempotencyKey\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion2\xb3\x01\n" +
	"\rRedbusService\x12N\n" +
	"\aProduce\x12\x1f.sergiusd.redbus.ProduceRequest\x1a .sergiusd.redbus.ProduceResponse\"\x00\x12R\n" +
	"\aConsume\x12\x1f.sergiusd.redbus.ConsumeRequest\x1a .sergiusd.redbus.ConsumeResponse\"\x00(\x010\x01B8\n" +
	"\x0fsergiusd.redbusB\vRedbusProtoP\x01Z\rapi/golang/pb\xa2\x02\x06Redbusb\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_goTypes = []any{
	(*ProduceRequest)(nil),                                          // 0: sergiusd.redbus.ProduceRequest
	(*ProduceResponse)(nil),                                         // 1: sergiusd.redbus.ProduceResponse
	(*ConsumeRequest)(nil),                                          // 2: sergiusd.redbus.ConsumeRequest
	(*ConsumeResponse)(nil),                                         // 3: sergiusd.redbus.ConsumeResponse
	(*ConsumeRequest_Connect)(nil),                                  // 4: sergiusd.redbus.ConsumeRequest.Connect
	(*ConsumeRequest_Result)(nil),                                   // 5: sergiusd.redbus.ConsumeRequest.Result
	(*ConsumeRequest_Connect_RepeatStrategy)(nil),                   // 6: sergiusd.redbus.ConsumeRequest.Connect.RepeatStrategy
	(*ConsumeRequest_Connect_RepeatStrategy_EvenConfig)(nil),        // 7: sergiusd.redbus.ConsumeRequest.Connect.RepeatStrategy.EvenConfig
	(*ConsumeRequest_Connect_RepeatStrategy_ProgressiveConfig)(nil), // 8: sergiusd.redbus.ConsumeRequest.Connect.RepeatStrategy.ProgressiveConfig
	(*ConsumeResponse_Connect)(nil),                                 // 9: sergiusd.redbus.ConsumeResponse.Connect
	(*ConsumeResponse_Message)(nil),                                 // 10: sergiusd.redbus.ConsumeResponse.Message
}
var file_api_proto_depIdxs = []int32{
	4,  // 0: sergiusd.redbus.ConsumeRequest.connect:type_name -> sergiusd.redbus.ConsumeRequest.Connect
	5,  // 1: sergiusd.redbus.ConsumeRequest.resultList:type_name -> sergiusd.redbus.ConsumeRequest.Result
	9,  // 2: sergiusd.redbus.ConsumeResponse.connect:type_name -> sergiusd.redbus.ConsumeResponse.Connect
	10, // 3: sergiusd.redbus.ConsumeResponse.messageList:type_name -> sergiusd.redbus.ConsumeResponse.Message
	6,  // 4: sergiusd.redbus.ConsumeRequest.Connect.repeatStrategy:type_name -> sergiusd.redbus.ConsumeRequest.Connect.RepeatStrategy
	7,  // 5: sergiusd.redbus.ConsumeRequest.Connect.RepeatStrategy.evenConfig:type_name -> sergiusd.redbus.ConsumeRequest.Connect.RepeatStrategy.EvenConfig
	8,  // 6: sergiusd.redbus.ConsumeRequest.Connect.RepeatStrategy.progressiveConfig:type_name -> sergiusd.redbus.ConsumeRequest.Connect.RepeatStrategy.ProgressiveConfig
	0,  // 7: sergiusd.redbus.RedbusService.Produce:input_type -> sergiusd.redbus.ProduceRequest
	2,  // 8: sergiusd.redbus.RedbusService.Consume:input_type -> sergiusd.redbus.ConsumeRequest
	1,  // 9: sergiusd.redbus.RedbusService.Produce:output_type -> sergiusd.redbus.ProduceResponse
	3,  // 10: sergiusd.redbus.RedbusService.Consume:output_type -> sergiusd.redbus.ConsumeResponse
	9,  // [9:11] is the sub-list for method output_type
	7,  // [7:9] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
