#!/usr/bin/env bash
# Managed downstream copy: edit lms-ai-multi-repo/.agents/scripts/readme-ai-index.sh.
# Builds a deterministic repository-wide map of tracked and ordinary untracked ReadmeAI.md files.

set -euo pipefail

pick_utf8_locale() {
  local candidate available
  available="$(locale -a 2>/dev/null || true)"
  for candidate in C.UTF-8 C.utf8 en_US.UTF-8 en_US.utf8; do
    if printf '%s\n' "$available" | grep -Fqx "$candidate"; then
      printf '%s\n' "$candidate"
      return 0
    fi
  done
  return 1
}

utf8_locale="$(pick_utf8_locale)" || {
  printf 'No UTF-8 locale is available to generate ReadmeAI.index.md\n' >&2
  exit 1
}
export LC_ALL="$utf8_locale" LANG="$utf8_locale"

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
repo_root="$(git -C "$script_dir/../.." rev-parse --show-toplevel)"
index_file="$repo_root/ReadmeAI.index.md"

list_files() {
  git -C "$repo_root" ls-files --cached --others --exclude-standard -- '*ReadmeAI.md' \
    | LC_ALL=C sort
}

extract_summary() {
  awk '
    function trim(s){ sub(/^[ \t]+/,"",s); sub(/[ \t]+$/,"",s); return s }
    BEGIN{ title=""; desc=""; sections=""; first_h2=""; nsec=0 }
    /^#[^#]/ && title=="" {
      t=$0
      sub(/^#+[ \t]*/,"",t)
      sub(/[ \t]*—[ \t]*ReadmeAI[ \t]*$/,"",t)
      sub(/[ \t]*–[ \t]*ReadmeAI[ \t]*$/,"",t)
      sub(/[ \t]*-[ \t]*ReadmeAI[ \t]*$/,"",t)
      sub(/[ \t]*ReadmeAI[ \t]*$/,"",t)
      title=trim(t); next
    }
    /^##[ \t]/ && nsec<3 {
      s=$0; sub(/^#+[ \t]*/,"",s); s=trim(s)
      if(first_h2=="") first_h2=s
      sections = sections (nsec>0 ? " · " : "") s
      nsec++
    }
    title!="" && desc=="" && $0 !~ /^[ \t]*$/ && $0 !~ /^#/ {
      desc=trim($0)
    }
    END{
      if(title=="") title=first_h2
      if(desc=="" && sections!="") desc="sections: " sections
      print title "\t" desc
    }
  ' "$1"
}

truncate_utf8() {
  perl -MEncode -e '
    my $raw = do { local $/; <STDIN> };
    $raw = "" unless defined $raw;
    my $text = Encode::decode("UTF-8", $raw, Encode::FB_CROAK);
    $text = substr($text, 0, 157) . "..." if length($text) > 160;
    print Encode::encode("UTF-8", $text);
  '
}

validate_utf8_file() {
  perl -MEncode -e '
    local $/;
    my $raw = <>;
    Encode::decode("UTF-8", $raw, Encode::FB_CROAK);
  ' "$1"
}

generate() {
  local count rel file dir summary title description label
  count="$(list_files | wc -l | tr -d ' ')"

  printf '%s\n' '# ReadmeAI module index'
  printf '\n'
  printf '%s\n' '> GENERATED by `.agents/scripts/readme-ai-index.sh`; do not edit manually.'
  printf '%s\n' '> Generate: `make readme-index`. Check: `make readme-index-check`.'
  printf '\n'
  printf 'Map of all `ReadmeAI.md` files (%s). Consult it before directory walk-up because\n' "$count"
  printf '%s\n' 'relevant context may be owned by a sibling subtree.'
  if (( count > 0 )); then
    printf '\n'
  fi

  while IFS= read -r rel; do
    file="$repo_root/$rel"
    dir="$(dirname "$rel")"
    [[ "$dir" == . ]] && label='(root)' || label="$dir"
    summary="$(extract_summary "$file")"
    title="${summary%%$'\t'*}"
    description="${summary#*$'\t'}"
    description="$(printf '%s' "$description" | truncate_utf8)"
    if [[ -n "$description" && "$description" != "$title" ]]; then
      printf -- '- [%s](%s) — **%s**: %s\n' "$label" "$rel" "$title" "$description"
    else
      printf -- '- [%s](%s) — **%s**\n' "$label" "$rel" "$title"
    fi
  done < <(list_files)
}

run_check() {
  local generated
  generated="$(mktemp "${TMPDIR:-/tmp}/readme-ai-index.XXXXXX")"
  generate > "$generated"
  validate_utf8_file "$generated"

  if [[ ! -f "$index_file" ]]; then
    printf 'ReadmeAI.index.md is missing. Run: make readme-index\n' >&2
    rm -f "$generated"
    exit 1
  fi
  if ! validate_utf8_file "$index_file"; then
    printf 'ReadmeAI.index.md contains invalid UTF-8. Run: make readme-index\n' >&2
    rm -f "$generated"
    exit 1
  fi
  if ! cmp -s "$index_file" "$generated"; then
    printf 'ReadmeAI.index.md is stale. Run: make readme-index\n' >&2
    diff "$index_file" "$generated" >&2 || true
    rm -f "$generated"
    exit 1
  fi

  rm -f "$generated"
  printf 'ReadmeAI.index.md is current.\n'
}

run_hook() {
  local staged_readmes unstaged_readmes untracked_readmes
  staged_readmes="$(git -C "$repo_root" diff --cached --name-only --diff-filter=ACDMR \
    | grep -E '(^|/)ReadmeAI\.md$' || true)"
  [[ -n "$staged_readmes" ]] || return 0

  unstaged_readmes="$(git -C "$repo_root" diff --name-only -- '*ReadmeAI.md' || true)"
  untracked_readmes="$(git -C "$repo_root" ls-files --others --exclude-standard -- '*ReadmeAI.md' || true)"
  if [[ -n "$unstaged_readmes" || -n "$untracked_readmes" ]]; then
    printf '%s\n' 'pre-commit: ReadmeAI.md has unstaged or untracked changes.' >&2
    printf '%s\n' 'Stage or revert them before committing so the index matches the committed snapshot.' >&2
    exit 1
  fi

  generate > "$index_file"
  validate_utf8_file "$index_file"
  git -C "$repo_root" add ReadmeAI.index.md
  printf 'pre-commit: ReadmeAI.index.md synchronized and staged.\n'
}

case "${1:-}" in
  --check) run_check ;;
  --hook) run_hook ;;
  "")
    generate > "$index_file"
    validate_utf8_file "$index_file"
    printf 'Generated %s\n' "$index_file"
    ;;
  *)
    printf 'Unknown argument: %s (expected --check, --hook, or no argument)\n' "$1" >&2
    exit 2
    ;;
esac
