#!/usr/bin/env bash
# Managed downstream copy: edit lms-ai-multi-repo/.agents/scripts/readme-ai-index.sh.
# Builds a deterministic repository-wide map of tracked and ordinary untracked ReadmeAI.md files.
# Each entry carries the document's context card (its opening paragraph), its H2 section titles and
# sibling Markdown files, so an agent can grep the index for a topic and land on the owning document.
# `--lint` reports documents that break the ReadmeAI contract (see .agents/guidance/readme-ai.md).

set -euo pipefail

pick_utf8_locale() {
  local candidate available
  available="$(locale -a 2>/dev/null || true)"
  for candidate in C.UTF-8 C.utf8 en_US.UTF-8 en_US.utf8; do
    if printf '%s\n' "$available" | grep -Fqx "$candidate"; then
      printf '%s\n' "$candidate"
      return 0
    fi
  done
  return 1
}

utf8_locale="$(pick_utf8_locale)" || {
  printf 'No UTF-8 locale is available to generate ReadmeAI.index.md\n' >&2
  exit 1
}
export LC_ALL="$utf8_locale" LANG="$utf8_locale"

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
repo_root="$(git -C "$script_dir/../.." rev-parse --show-toplevel)"
index_file="$repo_root/ReadmeAI.index.md"

list_files() {
  git -C "$repo_root" ls-files --cached --others --exclude-standard -- '*ReadmeAI.md' \
    | LC_ALL=C sort
}

# extract_summary <file>: prints "title<TAB>card<TAB>sections".
# card = the paragraph between the H1 and the first H2 (the context card); empty when the document
# starts with a section. sections = every H2 title joined with " · ".
extract_summary() {
  awk '
    function trim(s){ sub(/^[ \t]+/,"",s); sub(/[ \t]+$/,"",s); return s }
    BEGIN{ title=""; card=""; card_done=0; sections=""; nsec=0 }
    /^#[^#]/ && title=="" {
      t=$0
      sub(/^#+[ \t]*/,"",t)
      sub(/[ \t]*—[ \t]*ReadmeAI[ \t]*$/,"",t)
      sub(/[ \t]*–[ \t]*ReadmeAI[ \t]*$/,"",t)
      sub(/[ \t]*-[ \t]*ReadmeAI[ \t]*$/,"",t)
      sub(/[ \t]*ReadmeAI[ \t]*$/,"",t)
      title=trim(t); next
    }
    /^##+[ \t]/ {
      card_done=1
      if ($0 ~ /^###/) next
      s=$0; sub(/^#+[ \t]*/,"",s); s=trim(s)
      sections = sections (nsec>0 ? " · " : "") s
      nsec++
      next
    }
    title!="" && !card_done {
      if ($0 ~ /^[ \t]*$/) { if (card!="") card_done=1; next }
      l=$0; sub(/^>[ \t]*/,"",l)
      card = card (card=="" ? "" : " ") trim(l)
    }
    END{
      if(title=="") { split(sections, first, " · "); title=first[1] }
      print title "\t" card "\t" sections
    }
  ' "$1"
}

# sibling_docs <rel path of ReadmeAI.md>: other tracked *.md files in the same directory, as links.
sibling_docs() {
  local rel="$1" dir out="" name
  dir="$(dirname "$rel")"
  while IFS= read -r sib; do
    [[ "$(dirname "$sib")" == "$dir" ]] || continue
    name="$(basename "$sib")"
    [[ "$name" == ReadmeAI.md || "$name" == ReadmeAI.index.md ]] && continue
    out="$out${out:+, }[$name]($sib)"
  done < <(git -C "$repo_root" ls-files --cached --others --exclude-standard -- "$dir/*.md" | LC_ALL=C sort)
  printf '%s' "$out"
}

# truncate_utf8: caps the context card and flattens Markdown links to their text — a link relative to
# the document does not resolve from the repository root where the index lives.
truncate_utf8() {
  perl -MEncode -e '
    my $raw = do { local $/; <STDIN> };
    $raw = "" unless defined $raw;
    my $text = Encode::decode("UTF-8", $raw, Encode::FB_CROAK);
    $text =~ s/\[([^\]]+)\]\([^)]*\)/$1/g;
    $text = substr($text, 0, 237) . "..." if length($text) > 240;
    print Encode::encode("UTF-8", $text);
  '
}

validate_utf8_file() {
  perl -MEncode -e '
    local $/;
    my $raw = <>;
    Encode::decode("UTF-8", $raw, Encode::FB_CROAK);
  ' "$1"
}

generate() {
  local count rel file dir summary title card sections siblings label line
  count="$(list_files | wc -l | tr -d ' ')"

  printf '%s\n' '# ReadmeAI module index'
  printf '\n'
  printf '%s\n' '> GENERATED by `.agents/scripts/readme-ai-index.sh`; do not edit manually.'
  printf '%s\n' '> Generate: `make readme-index`. Check: `make readme-index-check`. Lint: `make readme-lint`.'
  printf '\n'
  printf 'Map of all `ReadmeAI.md` files (%s). Grep it for a topic before reading documents: every entry\n' "$count"
  printf '%s\n' 'is one line — directory, context card, `Sections:` (H2 titles) and `Also:` (sibling Markdown).'
  printf '%s\n' 'Relevant context may be owned by a sibling subtree, not only by the directory walk-up path.'
  if (( count > 0 )); then
    printf '\n'
  fi

  while IFS= read -r rel; do
    file="$repo_root/$rel"
    dir="$(dirname "$rel")"
    [[ "$dir" == . ]] && label='(root)' || label="$dir"
    summary="$(extract_summary "$file")"
    title="${summary%%$'\t'*}"
    card="${summary#*$'\t'}"; sections="${card#*$'\t'}"; card="${card%%$'\t'*}"
    card="$(printf '%s' "$card" | truncate_utf8)"
    siblings="$(sibling_docs "$rel")"
    line="- [$label]($rel) — **$title**"
    [[ -n "$card" && "$card" != "$title" ]] && line="$line: $card"
    [[ -n "$sections" ]] && line="$line Sections: $sections."
    [[ -n "$siblings" ]] && line="$line Also: $siblings."
    printf '%s\n' "$line"
  done < <(list_files)
}

# run_lint: structural checks from .agents/guidance/readme-ai.md. Warnings never fail; errors do.
# READMEAI_MAX_LINES (default 400) is the hard cap, READMEAI_REVIEW_LINES (default 250) the review trigger.
run_lint() {
  local max="${READMEAI_MAX_LINES:-400}" review="${READMEAI_REVIEW_LINES:-250}"
  local rel file lines summary title card sections errors=0 warnings=0 h2 ticket_h2
  while IFS= read -r rel; do
    file="$repo_root/$rel"
    lines="$(wc -l < "$file" | tr -d ' ')"
    summary="$(extract_summary "$file")"
    title="${summary%%$'\t'*}"
    card="${summary#*$'\t'}"; sections="${card#*$'\t'}"; card="${card%%$'\t'*}"
    h2="$(grep -cE '^## ' "$file" || true)"
    ticket_h2="$(grep -cE '^##+ .*\b[A-Z]{2,}-[0-9]+\b' "$file" || true)"
    if (( lines > max )); then
      printf 'error: %s has %s lines (cap %s): split by code owner, see readme-ai.md\n' "$rel" "$lines" "$max"
      errors=$((errors+1))
    elif (( lines > review )); then
      printf 'warning: %s has %s lines (review trigger %s): check for a child-module split\n' "$rel" "$lines" "$review"
      warnings=$((warnings+1))
    fi
    if [[ -z "$title" ]]; then
      printf 'error: %s has no H1 title\n' "$rel"
      errors=$((errors+1))
    fi
    if [[ -z "$card" ]]; then
      printf 'warning: %s has no context card (paragraph between H1 and the first section)\n' "$rel"
      warnings=$((warnings+1))
    fi
    if (( h2 == 0 && lines > 60 )); then
      printf 'warning: %s has %s lines and no ## sections\n' "$rel" "$lines"
      warnings=$((warnings+1))
    fi
    if (( ticket_h2 > 0 )); then
      printf 'warning: %s has %s section title(s) named by ticket id; name the concept, keep the ticket inline\n' "$rel" "$ticket_h2"
      warnings=$((warnings+1))
    fi
  done < <(list_files)
  printf 'ReadmeAI lint: %s error(s), %s warning(s).\n' "$errors" "$warnings"
  (( errors == 0 ))
}

run_check() {
  local generated
  generated="$(mktemp "${TMPDIR:-/tmp}/readme-ai-index.XXXXXX")"
  generate > "$generated"
  validate_utf8_file "$generated"

  if [[ ! -f "$index_file" ]]; then
    printf 'ReadmeAI.index.md is missing. Run: make readme-index\n' >&2
    rm -f "$generated"
    exit 1
  fi
  if ! validate_utf8_file "$index_file"; then
    printf 'ReadmeAI.index.md contains invalid UTF-8. Run: make readme-index\n' >&2
    rm -f "$generated"
    exit 1
  fi
  if ! cmp -s "$index_file" "$generated"; then
    printf 'ReadmeAI.index.md is stale. Run: make readme-index\n' >&2
    diff "$index_file" "$generated" >&2 || true
    rm -f "$generated"
    exit 1
  fi

  rm -f "$generated"
  printf 'ReadmeAI.index.md is current.\n'
}

run_hook() {
  local staged_readmes unstaged_readmes untracked_readmes
  staged_readmes="$(git -C "$repo_root" diff --cached --name-only --diff-filter=ACDMR \
    | grep -E '(^|/)ReadmeAI\.md$' || true)"
  [[ -n "$staged_readmes" ]] || return 0

  unstaged_readmes="$(git -C "$repo_root" diff --name-only -- '*ReadmeAI.md' || true)"
  untracked_readmes="$(git -C "$repo_root" ls-files --others --exclude-standard -- '*ReadmeAI.md' || true)"
  if [[ -n "$unstaged_readmes" || -n "$untracked_readmes" ]]; then
    printf '%s\n' 'pre-commit: ReadmeAI.md has unstaged or untracked changes.' >&2
    printf '%s\n' 'Stage or revert them before committing so the index matches the committed snapshot.' >&2
    exit 1
  fi

  generate > "$index_file"
  validate_utf8_file "$index_file"
  git -C "$repo_root" add ReadmeAI.index.md
  printf 'pre-commit: ReadmeAI.index.md synchronized and staged.\n'
}

case "${1:-}" in
  --check) run_check ;;
  --lint) run_lint ;;
  --hook) run_hook ;;
  "")
    generate > "$index_file"
    validate_utf8_file "$index_file"
    printf 'Generated %s\n' "$index_file"
    ;;
  *)
    printf 'Unknown argument: %s (expected --check, --lint, --hook, or no argument)\n' "$1" >&2
    exit 2
    ;;
esac
